### ISSUE TITLE
database not found

### ISSUE THREAD

**Issue by amorenew** [igniti0n/flutter_arhitect#5]
I tried to run the app and I got the following error
`PathNotFoundException (PathNotFoundException: Directory listing failed, path = '/data/user/0/com.example.flutter_arhitect/app_flutter/flutter_arhitect/database/' (OS Error: No such file or directory, errno = 2))`
I wonder what is the database directory?

**Comment by igniti0n** [comment]
You can find interaction with the database in the `file_service.dart` file. Data is just stored and read from files.

What platform are you running on?

**Comment by amorenew** [comment]
@igniti0n macOS
